### ISSUE TITLE
Slide left or right to reveal timestamp

### ISSUE THREAD

**Issue by ProKashif** [MessageKit/MessageKit#1006]

**Comment by nathantannar4** [comment]
Is this a question? If you asking if it's supported no it is not. You would have to implement it somehow yourself

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ded** [comment]
Are there plans to implement this in the future? the original question was making a reference to how iMessage works. Eg: Rather than displaying a timestamp underneath every single message, the user can swipe left to reveal the time.
![AEA01CA3-FCA9-47AA-B8DD-D08CFFD69D02](https://user-images.githubusercontent.com/372683/75199028-e7ea2400-5716-11ea-84c1-747474db2f45.GIF)

**Comment by dhaneshgosai** [comment]
Any update on this feature?

**Comment by fukemy** [comment]
@dhaneshgosai lul read news first
