### ISSUE TITLE
Cut initials in avatar view.

### ISSUE THREAD

**Issue by iBolom** [MessageKit/MessageKit#103]
Well, i attached screenshot where you can see that some initials in avatar view are cut.
So i can take this issue on myself and try to fix it.
<img width="320" alt="screen shot 2017-09-06 at 12 16 33 pm" src="https://user-images.githubusercontent.com/14849933/30107769-097adbc4-9300-11e7-8d67-6537a06a9a3a.png">

**Comment by gungorbasa** [comment]
@SD10 @MacMeDan I know what the problem is but we have a bigger problem. There are so many hardcoded size values so this causes inconsistencies(Also sort of cause of this problem as well). For example, we can use `MessageLayoutDelegate` to set size of an avatar, but even though the size is set, we create avatar itself `30x30` in `AvatarView`. I am not sure what kind of approach we should take to fix this. Somehow, whenever user set a size in `func avatarSize(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView)` we should be able to update `AvatarView` accordingly.

As a quick fix to this problem just set the return size from `func avatarSize(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView)` `40x40` and in `AvatarView` class set frame width and height to `40x40` as well. Also, we should update `textRect` accordingly(I set it to `30x30` and it looks good.). You can see the result below.

<img width="310" alt="screen shot 2017-09-08 at 12 00 00 pm" src="https://user-images.githubusercontent.com/2487031/30227106-4ae278d6-948d-11e7-8477-88189d6d1d34.png">

**Comment by MacMeDan** [comment]
@gungorbasa I think you have a really nice solution there. Would you mind creating a pull request so we can see how you fixed it. This may be perfect. I really like just making the text fit with the space given I think that is great. 
Edit: #104

**Comment by SD10** [comment]
@gungorbasa Yes you're right the AvatarView needs to be dynamic to support any given size and not just `30`x`30`. I'd be open to a PR if you want to tackle this. Just don't touch any other file except `AvatarView` and `MessagesViewController` because they have been heavily changed on my local copy. ❤️

**Comment by gungorbasa** [comment]
@MacMeDan @SD10 I have a solution to the problem. Which branch should I do PR?

**Comment by SD10** [comment]
@gungorbasa submit a PR to v0.7.0 please 👍
