### ISSUE TITLE
Add a totally custom input view 

### ISSUE THREAD

**Issue by pietrozuco** [MessageKit/MessageKit#1047]
Hello

Our app uses a chat as its main interface to guide the customer in the signup process. We would like to replace our current chat system and use MessageKit. I've been playing a bit with it, and I noticed that although the MessageInputBar can be customisable, what we need is a further level of customisation. I need to be able to insert a custom view and interface it with the main chat. I was thinking of getting the MessagesViewController embedded in a container and avoid making it the first responder. Then add our custom views at the bottom and interface them with the chat. 
This might work, but it doesn't look clean. Is there a better way to accomplish this?

I attached a screenshot of what we would it to look like. 

MessageKit version latest from pods
Xcode 10.2
Swift 5
iPhone only

![messagekit_inputview](https://user-images.githubusercontent.com/228305/55726115-fc420700-5a06-11e9-832e-671d46579023.jpg)

**Comment by nathantannar4** [comment]
@pietrozuco are you doing you are using Swift 5? In which case you can use the Swift 5 branch which has 3.0.0 changes. 

You have at least two options with MessageKit 3.0.0
1. You can override the `middleContentView` with a custom view of your own, see the Example on the development branch where I place a "join chat" button in the MessageInputBar instead of the InputTextView
2. Override the InputAccessoryView of the MessagesViewController with your own

If you are using 3.0.0, option one is the easiest

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
