### ISSUE TITLE
Input Bar appears when trying to dismiss image view

### ISSUE THREAD

**Issue by hhoangna** [MessageKit/MessageKit#1094]
Sorry I not good at English
In Chat view controller, I present a ImageView that has dismissal.
When i just try dismiss and release, not dismiss completion. inputbar automatic appear.
Please help me to prevent inputbar appear
![ezgif com-optimize](https://user-images.githubusercontent.com/26923574/59403581-5c6d7480-8dcd-11e9-91f5-19b80d3ef24f.gif)

**Comment by nathantannar4** [comment]
It looks like an error in your view controller transition. Your image preview controller is dismissed and then your messages controller becomes the first responder so the input bar appears. You should only dismiss the image preview controller when the drag gesture on the image ends 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hhoangna** [comment]
I have solution that present my image preview controller in new UIWindow. But input bar resign after i present new uiwindow. how can i prevent it?

**Comment by nathantannar4** [comment]
Call `becomeFirstResponder()` on the controller with the input bar you want to show. This is because the input bar is an inputAccessoryView. I recommend the apple docs on this as it's well documented how UIKit controls accessory view appearance

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
