### ISSUE TITLE
Load previous messages breaks custom cells layout

### ISSUE THREAD

**Issue by AdamLee321** [MessageKit/MessageKit#1105]
I created a custom cell, everything works fine and looks as it should until I load the previous messages which causes the custom some cells to span the width of the device. 

This is how it looks before refreshing:
![Screenshot 2019-06-19 at 10 41 09](https://user-images.githubusercontent.com/22890658/59755289-946a3100-927f-11e9-815c-beb3e6e33410.png)

Once I refresh this happens:
![Screenshot 2019-06-19 at 10 48 12](https://user-images.githubusercontent.com/22890658/59755419-c67b9300-927f-11e9-9902-f53fa7c3c23a.png)

Any help with this is much appreciated I have tried a few solutions but nothing seems to work.

- Version of MessageKit: 1.0.0
- iOS version: 12.1
- Swift Version: 4
- Devices: Simulator and all devices.
- Reproduceable: No

**Comment by nathantannar4** [comment]
Can you please share what solutions you have tried yourself?

Also, since this is custom there is very little I have to go off of, can you please share more on how you specify the sizing for your custom cells?

Have you tried updating to MessageKit 3.0, or at the very least 2.0?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
@AdamLee321 Going to close this for now. If you are still having the issue, please post a code snippet of your custom cell sizing code. Thanks 👍
