### ISSUE TITLE
MessagesViewController in SwiftUI freezes on keyboard input

### ISSUE THREAD

**Issue by dostrander** [MessageKit/MessageKit#1210]
- What version of MessageKit are you using?
`3.0.0-swift5` (sha: `e892a9ca49ebe6d82684d3a93ad84021fa23e2c6`)
- What version of iOS are you running on?
13.1
- What version of Swift are you running on?
5
- What device(s) are you testing on? Are these simulators?
iPhone11 Pro simulator
- Is the issue you're experiencing reproducible in the example app?
I will attach a sample app that reproduces the error.

Hello all,

I am trying to use a MessagesViewController in a SwiftUI and am running into an issue where when I try to type into the textfield it will completely freeze the app. I am also getting the following error in the console log:

`API error: <_UIKBCompatInputView: 0x7fd5adc77540; frame = (0 0; 0 0); layer = <CALayer: 0x6000019ccba0>> returned 0 width, assuming UIViewNoIntrinsicMetric`

Doing some digging it looks to be in the input view. I'm not sure the best way to get around this issue.

I've attached a sample very small app that can reproduce the issue. Let me know if there is anything else I can help with

Thanks. 

[MessageKitTest.zip](https://github.com/MessageKit/MessageKit/files/3776240/MessageKitTest.zip)

**Comment by dostrander** [comment]
I have just tested this with the device and it looks to be fine. Must be some sort of simulator bug

**Comment by ericpalyan** [comment]
I get this issue as well. I'm not sure if both of our problems are caused by the same source but I have narrowed down to the simple fact that....
- Whenever another user sends a message the whole view controller starts getting extremely laggy. The more messages there are the worse it gets. If the current user is sending messages the problem does not appear.

Any ideas what could be causing this? 

edit: 
I also get the following error when dismissing the keyboard. (again only happens during the condition above)....

[View] First responder warning: '<InputBarAccessoryView.InputTextView: 0x12d837200; baseClass = UITextView; frame = (0 0; 270 38); text = ''; clipsToBounds = YES; gestureRecognizers = <NSArray: 0x2835bf810>; layer = <CALayer: 0x283a61760>; contentOffset: {0, 0}; contentSize: {270, 38}; adjustedContentInset: {0, 0, 0, 0}>' rejected resignFirstResponder when being removed from hierarchy
[Common] _BSMachError: port 13e27; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"

**Comment by Ryanauger95** [comment]
Getting the same issue as well. Can confirm that I have no issues on my physical phone.

**Comment by ajeetpratap** [comment]
I am getting the same issue as will. Any update on this.

**Comment by kinoroy** [comment]
This seems to be a more widespread issue with the Simulator and UITextField. ( https://forums.developer.apple.com/thread/122972 , https://stackoverflow.com/questions/58009155/keyboard-gets-stuck-in-ios-13-simulator ) Some users have had success with disabling automatic syncing of the pasteboard, and then restarting the simulator.
