### ISSUE TITLE
SwiftUI 

### ISSUE THREAD

**Issue by alelordelo** [MessageKit/MessageKit#1220]
Any plans for a SwiftUI version?

**Comment by kinoroy** [comment]
You can use MessageKit within SwiftUI ([see our example project for info](https://github.com/MessageKit/MessageKit/tree/master/Example/Sources/Views/SwiftUI)), but if you mean writing the library using SwiftUI, no there are currently no plans for that currently, and since one of the project goals is to support the last 3 iOS versions, I don't believe it will be in the roadmap for some time, as SwiftUI is iOS 13+ only.

**Comment by EnesKaraosman** [comment]
with the inspiration of this framework, I started writing a similar one in SwiftUI.
[Here is a link for repo](https://github.com/EnesKaraosman/SwiftyChat), any contribution or feedback is welcomed.
