### ISSUE TITLE
Random crash when there are multiple messages to load ([MessageKit.MessagesCollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:])

### ISSUE THREAD

**Issue by prgorasiya** [MessageKit/MessageKit#1242]
Hi,

I am using latest version of the framework and facing a crash which is random in behaviour.
Xcode console says 

`*** Assertion failure in [MessageKit.MessagesCollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:],  /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3698.140/UICollectionView.m:6149`

Basically whenever my app has about 10s of messages to load from firebase and perform 
```
self?.messagesCollectionView.reloadData {
      self?.messagesCollectionView.scrollToBottom(animated: true)
}
```

my app crashes. I can't seem to understand the reason. I even tried `self?.messagesCollectionView.scrollToBottom(animated: false)` but no luck.

One more thing to note is app comes to foreground/launched from push notification in most cases when app crashes.

Any help here would be useful for me.
Thank you.

**Comment by hyouuu** [comment]
It's probably related to https://github.com/MessageKit/MessageKit/issues/725 - I'll make a PR for it soon

**Comment by prgorasiya** [comment]
Any update on this yet?

**Comment by austinwright** [comment]
@prgorasiya Given the history on the linked issue, I would say that your problem is rooted in UIKit's internal behavior. As mentioned in the thread from 2018, you aren't required to call `MessagesCollectionViewscrollToBottom`.

@hyouuu merged a potential alternative scrolling API function, which is currently in beta if you want to try that out.

There is also an SO article from over 4 years ago that describes this exact problem: https://stackoverflow.com/questions/31436889/uicollectionview-assertion-failure-in-uicollectionview-updatewithitemstentat. Given that your problem has been manifesting when your app comes to the foreground or after tapping a push notification, it would appear that this is likely the problem rather than having to do with MessageKit specifically.

I have also observed that since iOS 13 came out and UIKit was updated, viewWillAppear/viewDidAppear may no longer be called when a view is updated and/or the navigation hierarchy is changed when an app is in the background. Animations and non-animations also appear to behave differently in these cases compared to iOS 12.

One other thought to try: You might want to register for an application notification for when your app becomes active in order to more reliably load new messages.
