### ISSUE TITLE
Add long press callback

### ISSUE THREAD

**Issue by busu90** [MessageKit/MessageKit#1328]
Is there a way to add long press to the default text cell?

**Comment by isupremedyou** [comment]
@busu90 Can you please provide more information? Currently the default text cell implements [this](https://developer.apple.com/documentation/uikit/uicollectionviewdelegate/1618010-collectionview) method to allow for the `copy` menu item to appear. However starting in iOS 13, long press uses a new API.

You will need to provide more information about what you are wanting to accomplish before I can help.

**Comment by JippeJoosten** [comment]
@isupremedyou I would like to edit the menu, for example, to save an image to the library. 
Or a step up from there adding my own context menu so I can create menu's like iMessage does to like a message or reply for example.

**Comment by isupremedyou** [comment]
@JippeJoosten sounds great. Let's start with supporting iOS 13 as the collectionView menu item API's are deprecated:

## collectionView(_:contextMenuConfigurationForItemAt:point:)
In order to supply a contextual menu, you must first implement this method.

This method returns a `UIContextMenuConfiguration`. When you initialize a `UIContextMenuConfiguration`, it asks for 3 parameters, `identifier`, `previewProvider`, and `actionProvider`

### identifier
You will want to pass in an `identifier` as the first parameter and the identifier must conform to `NSCopying`. I'll explain why you will want to use this later, but remember that the remaining context menu API's for collection views don't go off of indexPath, so this identifier with help you later. An easy way to get an `NSCopying` identifier is to do the following:
```
let identifier = NSString(string: message.messageId)
```

### previewProvider
I won't cover this in depth right now, but basically this previewProvider allows you to provide a view controller to show with the context menu, rather than just highlighting the element being long pressed. This is the difference between how the native Photos app implements its context menu when you long press on an image thumbnail vs. how Messages implements its context menu when you long press on a text message.

### actionProvider
The action provider is a closure that returns a `UIMenu`. A UIMenu takes in several parameters so i'll just show an example of how you could implement a menu with a copy action. The closure might look something like this:
```
let message = messagesList[indexPath.section]
UIContextMenuConfiguration(identifier: identifier, previewProvider: nil, actionProvider: { (suggestedActions) -> UIMenu? in
    var actions = [UIAction]()
    switch message.kind {
    case .text(let text):
        let copy = UIAction(title: "Copy", image: UIImage(systemName: "doc.on.doc")) {
            let pasteboard = UIPasteboard.general
            pasteboard.string = text
        }
        actions.append(copy)
    default:
        break
    }
    if actions.isEmpty {
        return nil 
    } else {
        return UIMenu(title: "", image: nil, children: actions)
    }
})
```

## collectionView(_:previewForHighlightingContextMenuWithConfiguration:) AND collectionView(_:previewForDismissingContextMenuWithConfiguration:)
With MessageKit collection view cells, it is important to implement these 2 methods. These methods allow you to specify which part of the cell should be highlighted. In MessageKit the cell includes more than just the message bubble, and you likely don't want [all of these subviews](https://github.com/MessageKit/MessageKit#cell-structure) being highlighted alongside your context menu.

These two methods don't provide you with an indexPath, so now our `NSCopying` identifier comes in handy because we can determine which cell and what kind of cell we are creating a targeted preview for. Typically you want to return the exact same targeted preview in both of these methods so here is what a sample implementation would look like:
```
fileprivate func makeTargetedPreview(for collectionView: UICollectionView, with configuration: UIContextMenuConfiguration) -> UITargetedPreview? {
    guard let messagesCollectionView = collectionView as? MessagesCollectionView,
        let identifier = configuration.identifier as? String,
        let section = messagesList.firstIndex(where: { $0.messageId == identifier }),
        let messageContentCell = messagesCollectionView.cellForItem(at: .init(row: 0, section: section)) as? MessageContentCell else {
            return nil
    }
    let messageContainerView = messageContentCell.messageContainerView
    let parameters = UIPreviewParameters()
    if let shapeLayer = messageContainerView.layer.mask as? CAShapeLayer,
        let shapePath = shapeLayer.path {
        parameters.visiblePath = UIBezierPath(cgPath: shapePath)
    }
    return UITargetedPreview(view: messageContainerView, parameters: parameters)
}
func collectionView(_ collectionView: UICollectionView, previewForHighlightingContextMenuWithConfiguration configuration: UIContextMenuConfiguration) -> UITargetedPreview? {
    return makeTargetedPreview(for: collectionView, with: configuration)
}
func collectionView(_ collectionView: UICollectionView, previewForDismissingContextMenuWithConfiguration configuration: UIContextMenuConfiguration) -> UITargetedPreview? {
    return makeTargetedPreview(for: collectionView, with: configuration)
}
```

I've only shared a tiny amount in explaining this, so I would strongly recommend you read up on contextual menus in iOS 13 to educate your own implementation. Here is the best article I read when learning about these new APIs:
https://kylebashour.com/posts/context-menu-guide

**Comment by fukemy** [comment]
hi @isupremedyou , i have previewProvider but can not click, can u help? https://stackoverflow.com/questions/66631995/swift-custom-context-menu-previewprovider-can-not-click-any-view-insideusing-ta
