### ISSUE TITLE
Messages Loading Take Long Time In Chat Room

### ISSUE THREAD

**Issue by mgolam** [MessageKit/MessageKit#1351]
Hi There, when i opening chat room then all conversations keep scrolling to end of the message. If huge conversations then app crashing. It should be opened just last conversation promptly, not loading from the begging all messages. Will be highly appreciated as fast as fix this issue. Thank you.

**Comment by kinoroy** [comment]
Hi @mgolam if you don't want the entire conversation to load at once then you need to implement some type of pagination logic in your message data source. This would mean initializing the messages data source with only a few messages, and then lazily fetching more as the user scrolls up (and purging messages that have gone far off the screen if needed). There's currently no built-in MessageKit pagination helpers although its something that we might add in the future. You can refer to the conversation in #441 for this feature request and some ideas to implement what you're looking for.   I'm sorry that I can't give a time estimation or promise when we will add something like this as we're all just a group of volunteers but I hope this helps. 

If I misunderstood your request also let me know.

**Comment by martinpucik** [comment]
Or you can use [this](https://developer.apple.com/documentation/uikit/uicollectionviewdatasourceprefetching/prefetching_collection_view_data) to add pagination in the current MessageKit version on your own. Just load previous messages when prefetch data source invokes prefetch request for `IndexPath(0, 0)`

**Comment by anmolrajpal** [comment]
Hi @kinoroy I'm digging up a lot but couldn't figure out a way to animate the scroll after pagination. A great example is WhatsApp, as the user scrolls up, it beautifully animates the scroll offset without freezing the UI. 

I tried and the best I can figure out the way is:
```
func reloadDataKeepingOffset() {
    let offset = self.messagesCollectionView.contentOffset.y + messagesCollectionView.adjustedContentInset.bottom + messagesCollectionView.verticalScrollIndicatorInsets.bottom
    let oldY = self.messagesCollectionView.contentSize.height - offset
    self.messagesCollectionView.reloadData()
    self.messagesCollectionView.layoutIfNeeded()
    let y = self.messagesCollectionView.contentSize.height - oldY
    let newOffset = CGPoint(x: 0, y: y)
    UIView.animate(withDuration: 0.1, delay: 0, options: .beginFromCurrentState, animations: {
         self.messagesCollectionView.contentOffset = newOffset
    }) { _ in  }
}
```
I call the above method after loading the data.

**The problem is, when I use animation, it animates to that last offset, i.e, not respecting the offset "postion_to_be_at" as user scrolls.
When I don't use animation, it maintains offset, but doesn't animate the scroll.**

Please give me some suggestions, how can we get something like WhatsApp does in its scroll.
