### ISSUE TITLE
How to set height of messageInputBar ?

### ISSUE THREAD

**Issue by AwaisFayyaz** [MessageKit/MessageKit#1354]
I want to set custom height for messageInputBar of MessagesViewController. Default height is small. I know that if i set large enough font, height will be automatically increased. but i don't want to increase the font. 

- What version of MessageKit are you using?
Latest version from pods 

- What version of iOS are you running on?
running on ios 12.4 and iOS 13.3

- What version of Swift are you running on?
5

- What device(s) are you testing on? Are these simulators?
iPhone 6 and iPhone 11 Pro Max Simulator

Any help would be much appreciated.

**Comment by kinoroy** [comment]
Hey @AwaisFayyaz 

Just to be clear, when you say increase the height without increasing the font size, do you just want to add padding to the MiddleContentView or InputTextView so that the text is centred with whitespace above and below it? Or do you want to set a static or minimum height for the blank state of the text view but still let the text fill that blank space as the user types more? 
![](https://raw.githubusercontent.com/MessageKit/MessageKit/master/Assets/InputBarAccessoryViewLayout.png)
If you want to pad the entire InputBar, MiddleContentView or InputTextView you can do that like:
````swift
// Entire InputBar padding
messageInputBar.padding.top = 50
messageInputBar.padding.bottom = 50
// or MiddleContentView padding
messageInputBar.middleContentViewPadding.top = 50
messageInputBar.middleContentViewPadding.bottom = 50
// or InputTextView padding
messageInputBar.inputTextView.textContainerInset.top = 50
messageInputBar.inputTextView.textContainerInset.bottom = 50
````
If you want to set a static height for the InputTextView you can do that as-well (be aware that doing this will stop the text view height from growing as the user types more text. But the user will be able to scroll through the text if there's overflow):
````swift
messageInputBar.shouldAutoUpdateMaxTextViewHeight = false
messageInputBar.setShouldForceMaxTextViewHeight(to: true, animated: false)
messageInputBar.maxTextViewHeight = 100
````
If you want to just have a _minimum_ height for the input text view and also continue to have the input view grow as the user types more text then I'm not sure if there's an easy or accessible way to do that apart from starting with the 'static height' method above and then dynamically calculating the height by yourself and updating as the text changes. We could perhaps expose a minimum height parameter in the future.

LMK if that helps.

**Comment by AwaisFayyaz** [comment]
I was able to increase the height using InputTextView padding. i wanted to achieve that "text is centred with whitespace above and below it". i achieved it using the following code.  

messageInputBar.inputTextView.textContainerInset.top = 50
messageInputBar.inputTextView.textContainerInset.bottom = 50

Thanks guys

**Comment by martinpucik** [comment]
That's great to hear @AwaisFayyaz. Thank you @kinoroy for the awesome response!
We should add this to our Example project #1355
