### ISSUE TITLE
Chat interaction without input bar and with buttons

### ISSUE THREAD

**Issue by nurlan-dzhavadov** [MessageKit/MessageKit#1390]
Hello!

I try to create a chat that is not linked to any external server, so where the user chats with the app itself. I want my user to interact by using the buttons in the custom cell and, hence, I need to remove input bar from my ViewController.  
Could you please help me to figure this out?

Review:
- remove input bar (where you type your message and press a "send" button)
- add custom cell with vertical stack, which contains buttons in it

I'm new to programming, so you'd help me a lot.

Here is my current code:

```
import UIKit
import MessageKit


public struct Sender: SenderType {
    public let senderId: String
    
    public let displayName: String
}

// Some global variables for the sake of the example. Using globals is not recommended!
let sender = Sender(senderId: "any_unique_id", displayName: "Steven")
let messages: [MessageType] = []

class PhoneAddictionChatVC: MessagesViewController {

    override func viewDidLoad() {
            super.viewDidLoad()
        
        messagesCollectionView.messagesDataSource = self
        messagesCollectionView.messagesLayoutDelegate = self
        messagesCollectionView.messagesDisplayDelegate = self
        
        let controller = MessagesViewController()
        controller.resignFirstResponder()
        controller.setTypingIndicatorViewHidden(true, animated: true)
        controller.hidesBottomBarWhenPushed = true
        }
    }


extension PhoneAddictionChatVC: MessagesDataSource {

    func currentSender() -> SenderType {
        return Sender(senderId: "any_unique_id", displayName: "Steven")
    }

    func numberOfSections(in messagesCollectionView: MessagesCollectionView) -> Int {
        return messages.count
    }

    func messageForItem(at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageType {
        return messages[indexPath.section]
    }
}

extension PhoneAddictionChatVC: MessagesDisplayDelegate, MessagesLayoutDelegate {}

```

**Comment by kinoroy** [comment]
Hey @dvlpd 

You can remove the inputBar by overriding the accessory view and returning nil. You'll also need to set an additional bottom inset to keep the messages out of the safe area on iPhone X+ devices.
```swift
class PhoneAddictionChatVC: MessagesViewController {

    override var inputAccessoryView: UIView? { return nil }
    // etc...

    override func viewDidLoad() {
            super.viewDidLoad()
            additionalBottomInset = UIApplication.shared.keyWindow?.safeAreaInsets.bottom ?? 0
            // etc...
    }
} 
```

For the custom cell, have a read of our [custom cell guide](https://github.com/MessageKit/MessageKit/blob/master/Documentation/CUSTOM_CELLS.md). You'll be able to add your stack view as a subview to your custom cell.
As an addendum to the custom cell guide, if you want your cell to look like the MessageKit ones with the bubble, then I suggest subclassing your custom cell from `MessageContentCell` instead of plain `UICollectionViewCell`, and adding your subview to the `messageContainerView` of your subclass.

**Comment by nurlan-dzhavadov** [comment]
It helped me) Thanks a lot!
