### ISSUE TITLE
Text Detectors not working on Custom Cell

### ISSUE THREAD

**Issue by rodriar** [MessageKit/MessageKit#1399]
Im using MessageKit 3.0.0 on iOS 13 and Swift 5. 
Im trying to have a hyperlink be shown on my custom cell message. I have implemented the MessageDisplayDelegate and enabledDetectors and detectorAttributes functions.
```
    messagesCollectionView.messagesDataSource = self
        messagesCollectionView.messagesLayoutDelegate = self
        messagesCollectionView.messagesDisplayDelegate = self
        messagesCollectionView.messageCellDelegate = self

   func detectorAttributes(for detector: DetectorType, and message: MessageType, at indexPath: IndexPath) -> [NSAttributedString.Key: Any] {
        return MessageLabel.defaultAttributes
    }

    func enabledDetectors(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> [DetectorType] {
        return [.url, .address, .phoneNumber, .date, .transitInformation]
    }
```
Maybe I need to implement something on the Custom cell that im missing?

**Comment by kinoroy** [comment]
Hey, @rodriar 

The MessagesDisplayDelegate methods are called by the cell itself, so you would need to call those methods within your custom cell and then set up some detectors. MessageKit doesn't know anything about how your custom cell works so it can't automatically wire anything up. That's why it says in the docs that `MessageDisplayDelegate` does not affect custom cells.

The detector logic is built into the `MessageLabel` class which is what the built-in cells use to display text. If you use a `MessageLabel` instead of a `UILabel` in your custom cell then you could make use of the detector logic, and even wire it up to work with the MessageDisplayDelegate. 

If you followed the [custom cell guide ](https://github.com/MessageKit/MessageKit/blob/master/Documentation/CUSTOM_CELLS.md) you should have a `configure` method in your cell, you could add something like this to make your `MessageLabel` pick up the enabled detectors from your MessagesDisplayDelegate (this code is taken partly from the built-in `TextMessageCell` implementation):

````swift
    /// The label used to display the message's text.
    open var messageLabel = MessageLabel()

    open func configure(with message: MessageType, at indexPath: IndexPath, and messagesCollectionView: MessagesCollectionView) {

        guard let displayDelegate = messagesCollectionView.messagesDisplayDelegate else {
            fatalError(MessageKitError.nilMessagesDisplayDelegate)
        }

        let enabledDetectors = displayDelegate.enabledDetectors(for: message, at: indexPath, in: messagesCollectionView)

        messageLabel.configure {
            messageLabel.enabledDetectors = enabledDetectors
            for detector in enabledDetectors {
                let attributes = displayDelegate.detectorAttributes(for: detector, and: message, at: indexPath)
                messageLabel.setAttributes(attributes, detector: detector)
            }

            switch message.kind {
            case .text(let text), .emoji(let text):
                let textColor = displayDelegate.textColor(for: message, at: indexPath, in: messagesCollectionView)
                messageLabel.text = text
                messageLabel.textColor = textColor
                if let font = messageLabel.messageLabelFont {
                    messageLabel.font = font
                }
            case .attributedText(let text):
                messageLabel.attributedText = text
            default:
                break
            }
        }

            // ... Rest of your cell config

    }
````

**Comment by rodriar** [comment]
Hey @kinoroy, 
This worked out perfectly.
Thank you very much for your help and patience!

**Comment by rodriar** [comment]
Another doubt im having is why I cant set the color of the url/email/tel number even though its being set correctly here
```      switch message.kind {
            case .text(let text), .emoji(let text):
                let textColor = displayDelegate.textColor(for: message, at: indexPath, in: messagesCollectionView)
                messageLabel.text = text
                messageLabel.textColor = textColor
                if let font = messageLabel.messageLabelFont {
                    messageLabel.font = font
                }
            case .attributedText(let text):
                messageLabel.attributedText = text
            default:
                break
            }
        }
```
Instead of having the real color its just black.

**Comment by monstermac77** [comment]
I ran into something similar to this, which was that the URL tapping wasn't working on custom cells. Basically all of the example code for creating a custom cell leaves out this one critical method you have to implement on your custom cell class in order to get touches passed to the label so it can handle them: 

```
open override func cellContentView(canHandle touchPoint: CGPoint) -> Bool {
      return messageLabel.handleGesture(touchPoint)
}
```
