### ISSUE TITLE
viewDidLoad on MessageViewController not called

### ISSUE THREAD

**Issue by Mactacs** [MessageKit/MessageKit#1415]
Hi! I'm starting learning swift in iOS. Thank you for this great api I was able to use this on my chat app project. Now the issue I had encountered was when I added a MessageViewController as a subclass to my ViewController class, the viewDidLoad of MessageViewController was not called. And I tried putting a print log inside viewDidLoad in MessageViewController on the example that is provided by this repository and found out that viewDidLoad was called. Right now it gave me confusion on what I have been lacking. 

class TestViewController : MessageViewController {

}

   open class MessagesViewController: UIViewController,UICollectionViewDelegateFlowLayout, UICollectionViewDataSource         
   {
        ........
        ........

        open override func viewDidLoad() {
             print("HELLO WORLD") // No print logs found
        }
   }

**Comment by austinwright** [comment]
Did you call `super` from your implementation of `viewDidLoad` in `TestViewController`?

**Comment by kinoroy** [comment]
Hi @Mactacs,

Is there a particular reason why you are creating your own class called `MessagesViewController` which has the same name as `MessagesViewController` in MessageKit? I would advise that you never create your own classes which name-clash with libraries that you're using because your new class will take precedence and you will no longer be using the class from MessageKit.

Additionally, like Austin mentioned you should _always_ be calling the `super` implementation when you override methods from a class that you don't own, because that class might rely on that method being called as an implementation detail and when you override it without calling `super` you break that implementation. In this case, you should be calling `super.viewDidLoad()` .

This should be all you need to see the behaviour you're looking for: 
```swift
class TestViewController: MessagesViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        print("Hello world")
    }
}
```

**Comment by Mactacs** [comment]
Actually @kinoroy , I did not create a new MessageViewController. The default MessageViewController was the one I used. My main goal was to edit the MessagesViewController on collectionView to add a custom delete menu when message was long pressed in collectionView(......) ->Bool and I edit the MessagesViewController but the changes I made to the MessagesViewController did not work. I found out that the viewDidLoad was not called compared to the example given by this repository. Am I missing something?

**Comment by Mactacs** [comment]
> Did you call `super` from your implementation of `viewDidLoad` in `TestViewController`?

Yes, I did a call super.viewDidLoad() inside my TestViewController.

**Comment by kinoroy** [comment]
@Mactacs You generally shouldn't need to edit the library code, and if you do and you're using Cocoapods then your changes will be overwritten anyways, so I suggest that you don't do it. If you need to modify behaviour of `MessagesViewController`, do it in your subclass instead of editing the library code. You can add a delete menu item by overriding the following methods in your `TestViewController`: 

``` swift
     override func collectionView(_ collectionView: UICollectionView, canPerformAction action: Selector, forItemAt indexPath: IndexPath, withSender sender: Any?) -> Bool {
            
            if action == NSSelectorFromString("delete:") {
                return true
            } else {
                return super.collectionView(collectionView, canPerformAction: action, forItemAt: indexPath, withSender: sender)
            }
        }
        
    override func collectionView(_ collectionView: UICollectionView, performAction action: Selector, forItemAt indexPath: IndexPath, withSender sender: Any?) {

            if action == NSSelectorFromString("delete:") {
                // 1.) Remove from datasource
                // insert your code here
                
                // 2.) Delete sections
                collectionView.deleteSections([indexPath.section])
            } else {
                super.collectionView(collectionView, performAction: action, forItemAt: indexPath, withSender: sender)
            }
        }
```

and extending `MessageCollectionViewCell` with the system `delete` method:

```swift
extension MessageCollectionViewCell {

    override open func delete(_ sender: Any?) {
        
        // Get the collectionView
        if let collectionView = self.superview as? UICollectionView {
            // Get indexPath
            if let indexPath = collectionView.indexPath(for: self) {
                // Trigger action
                collectionView.delegate?.collectionView?(collectionView, performAction: NSSelectorFromString("delete:"), forItemAt: indexPath, withSender: sender)
            }
        }
    }
}
```

[You can see a discussion here about it,](https://github.com/MessageKit/MessageKit/issues/706#issuecomment-395107647) and also how to add other custom menu items other than just the system copy/delete ones

**Comment by Mactacs** [comment]
@kinoroy I'm still confused because I added some inside the MessagesViewController in the Example project in this repository and it works perfectly but when I edit in my project it doesn't work. Why is that so?

**Comment by Mactacs** [comment]
It works perfectly. Thank you so much @kinoroy :)

**Comment by kinoroy** [comment]
@Mactacs The example project is a special case since it's a feature of Cocoapods, it's meant to allow library contributors to edit and test changes within the example project. But when you use MessageKit as a dependency in your own project, you're not given the same privilege to edit it. Glad I could help!
