### ISSUE TITLE
Dark mode support for Play button 

### ISSUE THREAD

**Issue by diegogarciar** [MessageKit/MessageKit#1435]
Hey, it would be great if we could change the color of the play button triangle to a color that supports dark mode

The suggested change would be in `PlayButtonView.swift`

where `setupView` would be as follows

```
 private func setupView() {
        triangleView.clipsToBounds = true
        if #available(iOS 13.0, *) {
            triangleView.backgroundColor = .label
        } else {
            triangleView.backgroundColor = .black
        }
        
        backgroundColor = .playButtonLightGray
    }
```

**Comment by kinoroy** [comment]
Hi @diegogarciar thanks for opening an issue! 🙂

The play button colour was fixed in #1386 to match iMessage behaviour, but that fix is still on the develop branch. This should be included in the next release. I don't have authority to do releases so at the moment I don't have an ETA on the next release but if you want, you can point cocoapods to use the develop branch for those changes.
