### ISSUE TITLE
ConcreteMessageType  seems to break existing code

### ISSUE THREAD

**Issue by eemi2010** [MessageKit/MessageKit#1468]
Hey there,

In my app I have a custom Message class that implements the MessageType protocol. In some places I cast the MessageType to my custom class. The code is now breaking if the cell is a LinkPreview cell because LinkPreview is a ConcreteMessageType which  also extends MessageType but is internal. 

What was the reason to make that class internal ?  What is the best way to support ConcreteMessageType with my own class ? 

Cheers.

**Comment by kinoroy** [comment]
Hey @eemi2010, thanks for opening an issue!

Looking at the code, I believe the ConcreteMessageType was used so that the LinkPreview could piggy back off of some of the TextMessage cell logic in the cell size calculator and the cell configure method without having to re-write it. 
However I agree that this is an issue for people casting to custom MessageType classes, I'll mark this as a bug and have a closer look to see how we can solve this.

**Comment by kinoroy** [comment]
@eemi2010 The fix for this should be now merged into the master branch. You can point your pod file to the master branch to get it now until we release another pod version. 

Thanks again for your report!
