### ISSUE TITLE
How to send video in messageKit

### ISSUE THREAD

**Issue by hungnt1486** [MessageKit/MessageKit#1473]
I have get trouble when i want to send video in message kit, i try more case but got fail.
i use MessageKit version 3.4.1
Please help me.
Thanks so much.

**Comment by kinoroy** [comment]
Hi @hungnt1486 ,

Can you please give an example of the code you use, and how it is failing (i.e. what errors you are getting / what is the expected behaviour vs what behaviour you are seeing). Please also have a look at [our example project](https://github.com/MessageKit/MessageKit/tree/master/Example), there's example code on how to set up your messages view controller.

**Comment by hungnt1486** [comment]
Hi @kinoroy 

I used source code demo and add more button support upload image and video, but uploaded image it work fine and then uploaded video i can't. Please help me.

Pls review images below.


![IMG_6191](https://user-images.githubusercontent.com/3970624/94385131-81c2f500-016e-11eb-93de-dc11e7a97654.PNG)
![IMG_6193](https://user-images.githubusercontent.com/3970624/94385141-87203f80-016e-11eb-91c5-17e2f3b049c4.PNG)
<img width="362" alt="IMG_6192" src="https://user-images.githubusercontent.com/3970624/94385151-8b4c5d00-016e-11eb-8f79-2d47a9fafd51.png">

**Comment by hungnt1486** [comment]
Morning @kinoroy ,

Pls help me.

I'm waiting for response.

**Comment by Kaspik** [comment]
I don't think this is bug/problem on MessageKit side - you need to process the video, take an image for preview, use it for cell, and process the new attachment type on your end. :)

**Comment by hungnt1486** [comment]
thanks so much @kinoroy , @Kaspik . I understood.
