### ISSUE TITLE
Lagging on iOS 16

### ISSUE THREAD

**Issue by hoanghung3249** [MessageKit/MessageKit#1752]
I tried it on iOS 16 and the lag appeared. The keyboard when appearing also covers the message cell part.
Everything still works fine on iOS 15.

**Comment by marune-jp** [comment]
same problem. the cell size calculation logic seems to be called too many times!
please fix this, even though the lag is a little bit better with 4.0.0, there seems to be another bug (textViewShouldBeginEditing of messageInputBar.inputTextView not called) so I cannot update.

**Comment by marune-jp** [comment]
by the way this lag happens with long messages, even as few as 15.
this is critical in my app; waiting eagerly for your answer.. 🙇‍♂️🙇

**Comment by Kaspik** [comment]
Can you repro this in our Example app? We are not experiencing anything in production even with iOS 16, so curious how to repro this.

**Comment by ffager83** [comment]
We're seeing something similar. Not clear yet what exactly is causing it - but yes, something that affecting the smooth scrolling in the chat view. Is it message size calculator or something else, I'm not 100% sure just yet.

Our current app in the AppStore, which was built earlier with Xcode 13 works just fine and the scrolling appears to be just as smooth as before, even running on iOS16 device.
But then, our newest version - which currently sits in TestFlight and built with Xcode 14, is causing the laggy or choppy scrolling.

I'm fully aware of the pretty extensive modifications to our chat view, (reactions, floating timelabels on top, custom message types....) that could be partly causing this, BUT theres clearly something that changed somewhere, since the AppStore version works just fine on the exact same device. 

And just to be clear; no changes were done to the chat view since last (appstore) version, we were just about to release a normal bugfix release but during the final testing we noticed that something is suddenly "broken" with the chat view, now we're trying to figure out what went wrong and this issue is something of a show stopper.
 
We gone through the diff, and nothing is linked to anything near the chat view since last working version.
No memory leaks has been detected surrounding the chat view controller.

And also, I'm not saying the seen issue would be directly inside MessageKit, it could also be due to changes in Xcode14 or iOS16 or something like that. (possible changes in UICollectionViewController, or something like that...?) 

We're currently using 3.7.0 release of MessageKit, both in the AppStore and the to-be-released TestFlight versions.
We wouldn't like to jump to 4.x version yet, or that wasn't planned for this release, but we might have to try that out as well.

Anyway, thats our story. Will update if something is found. 
Thank you and keep up the good work with MessageKit. 🤘🏼

**Comment by Kaspik** [comment]
Sorry to hear that, but if MessageKit version stayed the same, iOS 16 was tested for both, and the only difference is Xcode 14 - we might need to dig into that on that front. I don't think MessageKit 4.x introduced something new or different that would fix it, but worth trying if you can.

**Comment by marune-jp** [comment]
@Kaspik Here is a patch (remove .txt extension), repro'd using those steps:
1) install iOS 16 on test device
2) install newest Xcode
3) uninstall test app if present
4) clean build & run on test device

 I think too that that might be caused by something on Apple side.

BTW try to put more and more and more links (copy and paste on the patched file), pretty sure the lag will become more and more "problematic"

[repro.patch.txt](https://github.com/MessageKit/MessageKit/files/9861428/repro.patch.txt)

**Comment by kawashima-it** [comment]
@Kaspik and btw it didn't seem to repro before upgrading to iOS 16. but please check by yourself.

**Comment by Kaspik** [comment]
I tried my best but I'm still not seeing this. 😞 

https://user-images.githubusercontent.com/7204168/197895033-4c66115c-a722-4646-a8b9-a11805791b20.mp4

**Comment by ffager83** [comment]
Hmm, interesting.. We're still looking into this as well. I'm trying to disable all (or most) of the modifications and trying the MessageKit as vanilla as possible in our project. 

Anyway, thanks to both of you for your input into this. I'll report back if/when we find something.

**Comment by marune-jp** [comment]
@Kaspik @ffager83 If the conditions in my post are met, it should lag at least a little bit when decelerating, especially when URLs are shown during the deceleration.
Try the profiling tools of Xcode also, you should get some insights, especially about the most used (CPU-wise) functions etc...

**Comment by Kaspik** [comment]
Man, I even posted video with your own code where it's not happening.

This is open-source, you can debug it the same as me, if you are experiencing issues, feel free to fix them and open up a PR. 🙌🏼

**Comment by ffager83** [comment]
@kawashima-it yes, I'm noticing something similar with the URLs in messages in our code as well, but cannot yet reproduce it fully or all of the times, so I'm not 100% sure of it yet. Been playing around with the profiling tools today - and also disabling our modifications. 

@Kaspik Absolutely and fully agree with you. And thank you for taking time testing it! I would be more than happy to actually post a PR for this.

**Comment by Kaspik** [comment]
Also, we talked about that in other issue, but Xcode 14 is bad, try Xcode 14.1 RC 2 (still not yet out) that fixes a lot of performance issues. 🥺

**Comment by marune-jp** [comment]
@Kaspik cc @ffager83 
You never decelerate completely in the video && The video framerate is maybe not precise enough, this is why I suggested you try decelerating completely, close to where URLs are displayed.

Even if you don't get as much as lag as my app, I think you should still see that frames (pixels) are skipped, and so by tracking and fixing this phenomenon, I believe you might find some insights (and hopefully fix the bug indirectly)

Didn't mean to offend you, I am just giving you as much clues as possible (if you attack people giving you clues, then people will stop helping you making your software better & companies etc won't trust you)

As for me I am sorry I don't have the necessary time to debug collection view intricacies now.
This is as much as I can do.

I will post again if RC2 fixes the lag in some way.

**Comment by Kaspik** [comment]
Xcode 14.1 is out and I haven't seen any issues anymore.

**Comment by result0924** [comment]
I have also encountered this issue. The root cause is that every time I scroll, user data is accessed from the database. I am not sure why it works fine in Xcode 13, but causes lag in Xcode 14. If someone else has encountered a similar issue, they can look into this direction. Perhaps caching should also be used for the dateFormatter of the message date.

**Comment by marune-jp** [comment]
@Kaspik 
You have never seen the issue in the first place (as far as your posts say) so I don't really know what you mean by "I haven't seen any issues anymore."

(cc @result0924 ) This + the rudeness of other admins made me remake a whole new chat system from scratch using Swift UI (which turned out to work better).

**Comment by tmbiOS** [comment]
> I have also encountered this issue. The root cause is that every time I scroll, user data is accessed from the database. I am not sure why it works fine in Xcode 13, but causes lag in Xcode 14. If someone else has encountered a similar issue, they can look into this direction. Perhaps caching should also be used for the dateFormatter of the message date.

Hi! We had the same problem. We haven't got any idea how to fix it.

**Comment by tmbiOS** [comment]
> @Kaspik You have never seen the issue in the first place (as far as your posts say) so I don't really know what you mean by "I haven't seen any issues anymore."
> 
> (cc @result0924 ) This + the rudeness of other admins made me remake a whole new chat system from scratch using Swift UI (which turned out to work better).

Hi! Can you share some ideas or tutorials?

**Comment by result0924** [comment]
> > @Kaspik You have never seen the issue in the first place (as far as your posts say) so I don't really know what you mean by "I haven't seen any issues anymore."
> > (cc @result0924 ) This + the rudeness of other admins made me remake a whole new chat system from scratch using Swift UI (which turned out to work better).
> 
> Hi! Can you share some ideas or tutorials?

The root cause of my issue is that I retrieve the current sender from Core Data every time. To avoid unnecessary calls to Core Data, I cache the current user since it remains constant.

You could consider using Instruments to debug any issues that occur while scrolling, or use sample data instead of real data to aid in debugging.
```
public protocol MessagesDataSource: AnyObject {

    /// The `SenderType` of new messages in the `MessagesCollectionView`.
    func currentSender() -> SenderType
```

**Comment by tmbiOS** [comment]
> > > @Kaspik You have never seen the issue in the first place (as far as your posts say) so I don't really know what you mean by "I haven't seen any issues anymore."
> > > (cc @result0924 ) This + the rudeness of other admins made me remake a whole new chat system from scratch using Swift UI (which turned out to work better).
> > 
> > 
> > Hi! Can you share some ideas or tutorials?
> 
> The root cause of my issue is that I retrieve the current sender from Core Data every time. To avoid unnecessary calls to Core Data, I cache the current user since it remains constant.
> 
> You could consider using Instruments to debug any issues that occur while scrolling, or use sample data instead of real data to aid in debugging.
> 
> ```
> public protocol MessagesDataSource: AnyObject {
> 
>     /// The `SenderType` of new messages in the `MessagesCollectionView`.
>     func currentSender() -> SenderType
> ```

Thanks, bro! You saved my day!

**Comment by marune-jp** [comment]
> > @Kaspik You have never seen the issue in the first place (as far as your posts say) so I don't really know what you mean by "I haven't seen any issues anymore."
> > (cc @result0924 ) This + the rudeness of other admins made me remake a whole new chat system from scratch using Swift UI (which turned out to work better).
> 
> Hi! Can you share some ideas or tutorials?

I used basic SwiftUI without any libraries or whatever.
Don't know if this is OK for your use case though.
