### ISSUE TITLE
Location message is getting reloaded every time someone sent the message

### ISSUE THREAD

**Issue by timetraveler90** [MessageKit/MessageKit#251]
## General Information

* MessageKit Version: **0.9.0**

* iOS Version(s): **Any**

* Swift Version: **Any**

* Devices/Simulators: **Any**

* Reproducible in ChatExample? (Yes/No): **Yes**

##  What happened?
When at least one location message is sent and someone else, or even you, keep on sending new messages that location will get reloaded every single time someone send or you receive the message. Loading data every time can cause performance issues (and already causing) on a bit older devices and can affect data usage. Since i am not allowed to post video clips, here is the video example uploaded on dropbox, [here is the link](https://www.dropbox.com/s/75pxyb4lbgv16pn/Bug.mov?dl=0)

## What did you expect to happen?
Reload data should be avoided somehow in this particular case.

**Comment by SD10** [comment]
Thanks for reporting this @timetraveler90. I'm aware of the problem 😅. I think part of this is we are invalidating the layout too often, for example on height changes. I have that change locally but should push it immediately.

However, if you're calling `reloadData()` after sending a message then this problem is probably not avoidable. You would need to insert a new cell.

**Comment by SD10** [comment]
@timetraveler90 I'm hoping this is fixed in `v0.10.0`. Please re-open this issue if the problem persists. I appreciate you reporting this 👍
