### ISSUE TITLE
Experimental: Add shouldCacheLayoutAttributes(for message: MessageType) -> Bool

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#306]
### Reasoning
Some users may have messages that are displayed in cells with dynamic sizes: ie) Link previews.

### Problem Area
MessageKit caches the layout for messages after the first calculation by using the message ID. This means if a message is laid out with size A the first time it appears and then has size B the second time it appears, size A will be used. This requires the users to manually invalidate the cache for this message.

### Approach
I'm thinking if we add a `shouldCacheLayoutAttributes(for message: MessageType) -> Bool` method. The user can specify specific messages that will be used in cells with dynamic sizing, thus not having to worry about invalidating the cache.

cc @cwalo

**Comment by SD10** [comment]
A similar request would be `shouldInvalidateLayoutAttributes(for message: MessageType) -> Bool`.
I can't decide if we need both or if we should try to kill both birds with 1 stone.

**Comment by cwalo** [comment]
After playing with 0.10.x a bit, I see the most value in `shouldInvalidateLayoutAttributes(for message: MessageType) -> Bool`, but I can see cases where `shouldCache` might be handy . Speaking for myself, the reason some cells are dynamic (media in particular) is because we don't always know what they're ultimately going to display - photo messages from the user, for instance, create an "amendment" from our server that modifies the message in place. Backed by Realm (notifications), it's trivial to know when to invalidate. Regardless, I _do_ think we should avoid storing a reference to the `MessageType`, since these objects can be deleted or modified and without careful consideration on the part of the user, can lead to problems.

**Comment by SD10** [comment]
@cwalo I agree about trying not to hold any reference other than the id. As for `shouldInvalidateLayoutAttributes(for message: MessageType) -> Bool` my only concern is that we call this from a place where we can ensure it will only be called once per cycle.
