### ISSUE TITLE
Application freezes when (Select All | Select | Paste) is clicked in the Input bar.

### ISSUE THREAD

**Issue by azhararmar** [MessageKit/MessageKit#312]
## General Information

* MessageKit Version: 0.1.0

* iOS Version(s): 10.3.2

* Swift Version: 4

* Devices/Simulators: iPhone 6s Device & Simulator

* Reproducible in ChatExample? (Yes/No): Yes

##  What happened?
Write a message in the input bar. Hold the touch till the action tool tip is displayed and then click on Select or Select All or Paste. The application freezes.

## What did you expect to happen?
The application must not freeze when clicking on any of the clipboard action buttons.

**Comment by SD10** [comment]
Thanks for reporting this @azhararmar. I wonder where this came from 🤔. cc @nathantannar4

**Comment by nathantannar4** [comment]
This was a really good bug catch @azhararmar  @cwalo. I too can easily replicate the issue. After going through the stack trace on my own I can see that when a user selects text in the textView the intrinsicContentSize is invalidated A LOT. This may be because we invalidate it on the notification of .UITextViewTextDidChange which much be broadcasted a lot. In earlier versions it was added that in the calculation of the intrinsicContentSize that the InputTextViews content size also be invalidated. This seems to create a race condition! As when many .UITextViewTextDidChange notifications are sent it a circular cycle is created. Fix with PR #313

**Comment by SD10** [comment]
This is closed by #313 and on `master`. Please let us know if the problem persists 👍
