### ISSUE TITLE
Improve README and add MessageKit banner

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#46]
### Improve README and add MessageKit banner

The README could use some work 😅. 
I'll definitely work on updating it but this is also a good starter task.

We also could use a banner for the README. 
Something like the [JSQMessagesViewController banner](https://github.com/jessesquires/JSQMessagesViewController) would be great.

I'm open to other designs, I'm just not a good artist so I have no suggestions. 
Overall, I'd like to continue using the current **MessageKit** logo.

**Comment by mding5692** [comment]
Sorry mind posting the logo just in case somebody doesn't remember

**Comment by mding5692** [comment]
Just made some banners for fun right now, any comments on color scheme and other critiques? 

Basically copied over the JSQMessageViewController banner. 

I chose Orange as background colour (happy to change) because its a warmer and much more welcoming and happy colour and feels comfortable. 

![messagekitbanner1](https://user-images.githubusercontent.com/9067177/29157387-c986f264-7d74-11e7-8714-28e01951492c.png)
![messagekitbanner2](https://user-images.githubusercontent.com/9067177/29157388-c98720cc-7d74-11e7-8c20-a8ff5500dac7.png)
![messagekitbanner3](https://user-images.githubusercontent.com/9067177/29157389-c988d96c-7d74-11e7-91e3-47332a87cf4d.png)
![messagekitbanner4](https://user-images.githubusercontent.com/9067177/29157390-c98afe90-7d74-11e7-8e80-071ebc3b915b.png)

Noticed the subtitle font size is a bit small

**Comment by SD10** [comment]
@mding5692 Thanks for doing this! I definitely think we should continue to use a green color so it matches with our organization logo. You can increase the subtitle font size if you want or even remove the subtitle altogether. I can't critique more than that, better than anything I could've done. Maybe someone else has some input?

**Comment by mding5692** [comment]
@SD10 haha no problem, I do this Sketch-related stuff for fun anyways.
Heres green colour: 

![messagekitbanner2](https://user-images.githubusercontent.com/9067177/29158666-e2474c5e-7d79-11e7-987e-d5fc1887e22d.png)

Note that I dont actually know what colour green was used, so this is just roughly the same colour as JSQMessageViewController banner background colour

**Comment by omaralbeik** [comment]
I'm not a designer, but here is what I got 😅 
![1](https://user-images.githubusercontent.com/8127757/29166152-f2ad1160-7dcd-11e7-9743-c45e61167daa.jpg)
![2](https://user-images.githubusercontent.com/8127757/29166154-f2aff326-7dcd-11e7-87cd-ae36f92da886.jpg)
![3](https://user-images.githubusercontent.com/8127757/29166155-f2b15086-7dcd-11e7-8912-dbfcadf55801.jpg)
![5](https://user-images.githubusercontent.com/8127757/29166156-f2b5eda8-7dcd-11e7-8343-3edcc39e33da.jpg)
![4](https://user-images.githubusercontent.com/8127757/29166153-f2af7b62-7dcd-11e7-857a-e64cab45a212.jpg)

[sketch.zip](https://github.com/MessageKit/MessageKit/files/1214507/sketch.zip)

**Comment by omaralbeik** [comment]
@lionbytes would you be interested in this?

**Comment by mding5692** [comment]
@SD10 @omaralbeik Guess there should be a vote for which one should be a banner based on thumbs up, haha, I like @omaralbeik 's banners too, they stand out

**Comment by MacMeDan** [comment]
I personally still like the idea of changing the color to make us distinctly different then JSQ but am really ok. It does seem though like we have enough talent in this community to remake the logo if we wanted. 

As for the preposed banners I really like the first one. 
![screen shot 2017-08-10 at 9 47 29 am](https://user-images.githubusercontent.com/6182351/29179199-0c20e2f6-7db1-11e7-9213-3b6ddbe3c223.png)

but could also see this one being nice. 
![screen shot 2017-08-10 at 9 47 58 am](https://user-images.githubusercontent.com/6182351/29179200-0c2b4f98-7db1-11e7-981e-153deb0b0019.png)

I think seeing it on a page at the top with placeholder text would make a big difference also. I like @mding5692 colors here but am afraid that I like them because of the other colors around. The selection of colors are nice together and make it look neat but alone may not look as good. I would definitely suggest larger text for the subtitle.
![screen shot 2017-08-10 at 9 49 28 am](https://user-images.githubusercontent.com/6182351/29179378-7938688c-7db1-11e7-88aa-8261a1cc1518.png)
but all around great job guys.

**Comment by omaralbeik** [comment]
Here are some more variations

![1](https://user-images.githubusercontent.com/8127757/29181987-cae466a0-7e05-11e7-91af-f0a6a56fca10.jpg)
![2](https://user-images.githubusercontent.com/8127757/29181988-cb0bda6e-7e05-11e7-8c3b-ca1665f03c51.jpg)
![3](https://user-images.githubusercontent.com/8127757/29181989-cb2144c6-7e05-11e7-87e8-9d1d321cf6f8.jpg)
![4](https://user-images.githubusercontent.com/8127757/29181990-cb31b310-7e05-11e7-9520-f8b7fe731f87.jpg)
![5](https://user-images.githubusercontent.com/8127757/29181991-cb5dc2a2-7e05-11e7-8ade-c42b8398a336.jpg)

[MessageKit.sketch.zip](https://github.com/MessageKit/MessageKit/files/1215701/MessageKit.sketch.zip)

**Comment by mding5692** [comment]
Also for the README, I was thinking we could copy the ideas from a few other really good READMEs we've seen for now, i think its the easiest and most efficient way for now. 

I'm probably just gonna edit this post and list links of what I think are good READMEs and which bits we can use if you guys agree.

**Comment by MacMeDan** [comment]
@omaralbeik I like the first simple and elegant. 💯  I would spend any more time on this guys. It's not as important as the actual readme. and its allot easier to make it look good after we have something

**Comment by andreaantonioni** [comment]
@MacMeDan I like this one me too, I think this is the more elegant and clear at the moment.
![](https://user-images.githubusercontent.com/6182351/29179199-0c20e2f6-7db1-11e7-9213-3b6ddbe3c223.png)

**Comment by SD10** [comment]
I like the first one @omaralbeik posted too. 
Thank you @omaralbeik and @mding5692 for working on this 🍻 🎉 👍

**Comment by MacMeDan** [comment]
@omaralbeik Would you mind taking your first banner and saving it as an image. My sketch is outdated 😡 and I cannot open it.

**Comment by mding5692** [comment]
![messagekitbannerfinal](https://user-images.githubusercontent.com/9067177/29237677-366d283a-7ef1-11e7-8d34-1aed29bd1bf3.png)

Just opened up @omaralbeik 's sketch files, heres the banner in .png file format :) hope it helps @MacMeDan

**Comment by omaralbeik** [comment]
@MacMeDan Sure, attached in logo.zip the first logo in .png, .jpg and .svg formats,
Please use the vector .svg image, this will make the logo looks sharper on high-res screens :)

example below

```html
<p align="center">
  <img src="https://cdn.rawgit.com/MessageKit/MessageKit/master/Assets/logo.svg" title="MessageKit logo">
</p>
```

[logo.zip](https://github.com/MessageKit/MessageKit/files/1219621/logo.zip)

**Comment by SD10** [comment]
@omaralbeik @MacMeDan @mding5692 @andreaantonioni Shame on you all. 
No one noticed the typo in **"An elegant messges library for iOS"**? :joy:

**Comment by omaralbeik** [comment]
Oops!, my bad 🤒  😂 

[logo.zip](https://github.com/MessageKit/MessageKit/files/1220365/logo.zip)

**Comment by SD10** [comment]
@omaralbeik I already fixed it in the XML of the .svg 😎 Sorry to make you update it

**Comment by MacMeDan** [comment]
@SD10 I think you noticed. 🤣

**Comment by SD10** [comment]
![29179200-0c2b4f98-7db1-11e7-981e-153deb0b0019](https://user-images.githubusercontent.com/7445580/29254255-0f5f4b44-8057-11e7-8bc5-784b3619ba72.png)

~I think this one may be better if you guys look at the current master 🤔~
~@omaralbeik Can you provide the SVG for this one?~
EDIT: I'll handle it

**Comment by SD10** [comment]
Thank you for your help everyone 🎉

**Comment by omaralbeik** [comment]
@SD10 Here is the final logo in jpg, svg, sketch format

![mklogo](https://user-images.githubusercontent.com/8127757/29268665-74db4e7e-80f6-11e7-830f-17166a7ad7f2.jpg)

[mklogo.zip](https://github.com/MessageKit/MessageKit/files/1221977/mklogo.zip)

**Comment by MacMeDan** [comment]
@SD10 Why does the banner look like this 
![screen shot 2017-08-14 at 11 07 40 am](https://user-images.githubusercontent.com/6182351/29282687-f30ee636-80e0-11e7-9481-03016ddb3220.png)
and not the image above?

**Comment by MacMeDan** [comment]
So not to bring this up again but we are looking allot like `JSQ` to the point of confusion mostly because we are using the exact same phrase/logo/banner . I thought the consensus was moving more towards 
![screen shot 2017-08-14 at 11 31 21 am](https://user-images.githubusercontent.com/6182351/29283508-4722bd9e-80e4-11e7-8fb1-92a135b0161c.png)
this logo. Gives us a distinct look but keeps the JSQ Influences. Looks Clean and new. 
What say you?

**Comment by SD10** [comment]
@MacMeDan It looks like that because I thought I could get away with just pasting in an image of the logo to make the banner. I will replace it with the one Omar made :P

The reason why we're not going to use the MessageKit logo you mentioned, is because when I added it to the readme it looked horrendous. Like something from the web in 1999 😂. We definitely need a full green background.

**Comment by MacMeDan** [comment]
Sounds good.
