### ISSUE TITLE
Consider removing text(String) case of MessageData enum

### ISSUE THREAD

**Issue by cwalo** [MessageKit/MessageKit#617]
I'm proposing we remove the `text(String)` case of the MessageData enum and only provide the `attributedText(NSAttributedString)` case. 

Pros:
* It provides better performance under some circumstances
* Eases code complexity within MessageKit (see `TextMessageCell.configure(with...)`)

Cons:
* Slightly more work on behalf of the user to setup the strings on their MessageType model
* NSAttributedString API is not particularly friendly, but we could provide methods to ease the friction.
* Potential collisions with DataDetector attributes

**Comment by SD10** [comment]
This is a re-open of #205.

To be honest, I'm in favor of this because:
- We can eliminate `textMessageSizeCalculator` on `MessagesCollectionViewFlowLayout`
- We don't have to deal with the `messageLabel` property anymore
- No more confusing behavior from `textColor(for:at:in)` delegate method

It's less friendly than a `String` but I really recommend people use the library with `.attributedText(NSAttributedString)` anyways.

cc @MessageKit/contributors @MessageKit/core-team What do you think?

Edit: removing API breaking label since we only use it on PRs

**Comment by alessioarsuffi** [comment]
Seems reasonable for me 👍

**Comment by SD10** [comment]
Going to close this and reconsider again later 😓
