### ISSUE TITLE
The project name is like a library from Apple...

### ISSUE THREAD

**Issue by internalG** [MessageKit/MessageKit#63]
It's going to conflict with native name someday, my first impression...

**Comment by SD10** [comment]
@internalG Thanks for raising this issue. If that happens then we'll just have to rename the project.
They already have ChatKit as a private API so maybe they would use that name instead.
I think it's unlikely Apple would make a framework so specialized. It's possible they would use the name for another purpose but until then... 😃

**Comment by MacMeDan** [comment]
I actually really like that is sounds like a name apple would use. That is actually the goal. Of coarse though if they did we would adjust but till it's an issues we will carry on. Thanks for bringing it up and we hope you contribute everyone is welcome🕺🏿. I am going to close this issue since there is no action to be taken.
