### ISSUE TITLE
Chat reloads after appearing

### ISSUE THREAD

**Issue by AndriiPetrovDev** [MessageKit/MessageKit#637]
## General Information
Chat reloads after appearing. It looks not so nice as on another messengers 
* MessageKit Version:
Latest
* iOS Version(s):
10.3
* Swift Version:

* Devices/Simulators:
All
* Reproducible in ChatExample? (Yes/No):
Yes

##  What happened?
Chat reloads after appearing. 

## What did you expect to happen?
Chat already completely loaded when appears (at least visible cells).

**Comment by SD10** [comment]
@AndrewPetrov I need more information on this one. I don't understand what you're trying to convey here. Could be something that is specific to the example app?

**Comment by Luke47** [comment]
I think most messengers cache their chat history views, leading to a faster reload if the chat history is opened again, thus leading to almost no visible reloading going on.

However, @AndrewPetrov could it be that the reloading you mention is actually the chat history scrolling to the bottom? So, you open the history, the chat history is already loaded, but not scrolled to the bottom yet. So you see the oldest messages for a fraction of a second before the history scrolls down to the newest messages? You can try to comment out `self.messagesCollectionView.scrollToBottom()` in the demo project in the `viewDidLoad:` of ConversationViewController to check if this solves the "reload" issue for you.

Some other libraries offer the option to invert the chat history, so that you just need to reload the history and can get rid of the "scroll to bottom" part. I do not know, if this is something to consider for the development of this library or if there is some better way to solve the problem.

**Comment by hjuraev** [comment]
I have noticed same kind of behavior, I removed all codes related to scrolling to bottom but as soon as I assign datasource delegate to self, it reloads all data from chat Message Array variable. I have lazy loading in each message so this behavior is unwanted.

**Comment by boboxiaodd** [comment]
i use hide messageCollectionView  ， message page has a flash :(
````swift
override func viewDidLoad() {
        self.messagesCollectionView.isHidden = true
        load_message(isinit: true)
}

func load_message(isinit:Bool,page:Int = 1) {
     //.....
    DispatchQueue.main.async {
                self.messagesCollectionView.reloadData()
                self.messagesCollectionView.scrollToBottom(animated: false)
                Timer.after(TimeInterval(0.1), {
                    self.messagesCollectionView.isHidden = false
                })
      }
}
`````
