### ISSUE TITLE
Add support for any UIView as a message

### ISSUE THREAD

**Issue by JoshRobertsDev** [MessageKit/MessageKit#640]
Hello!

I think it'd be pretty useful to have an additional MessageData case to allow for any UIView to be displayed inside a message. This would allow us to build rich content messages without needing to have lots of setup code inside something like the messageStyle(...) DisplayDelegate function. Not sure what the progress on `case custom(Any)` is, or whether that's intended to work this way, but I was picturing something like `case customView(UIView)` which would pass all the heavy lifting into the view class itself.

Thanks for all the hard work with this lib 😃

**Comment by Luke47** [comment]
I am currently working on this as I also need a custom view (a link preview). The basic functionality is there on the development branch. It is not final yet according to the devs, but you can already check it out . You need to use the `.custom` data case, subclass `MessageCollectionViewCell` and override some other stuff. Then you can add any view you want. :)

**Comment by SD10** [comment]
Hey @JoshRobertsDev,

Thanks for opening this issue 😄 As @Luke47 already stated, this is the purpose of the `MessageData.custom(Any?)` case. Adding something like `.customView(UIView)` is a slippery slope. We can't continue to add a ton of enum cases whenever we need them, so `.custom` was meant to be a catch-all.

The other problem is `MessageData` is meant to store the underlying content of a `MessageType`. It's not meant to hold things related to styling. IMO, coupling the view with the model in this way is bad practice. My goal for MessageKit is to not manipulate the view hierarchy by adding/removing subviews in `cellForItem(at: IndexPath)` because I believe it's bad practice and it doesn't make use of cell re-use.

 However, if this is an acceptable design pattern -- clients can use `.custom(Any?)` however they choose.
