### ISSUE TITLE
Control chat bubble width

### ISSUE THREAD

**Issue by pbendersky** [MessageKit/MessageKit#651]
If there any way to make a chat bubble's width the full width of the messages collection view?

**Comment by SD10** [comment]
Not easy enough to be honest. We should have some sort of `fixedWidth` property 🤔

**Comment by pbendersky** [comment]
@SD10 thank you for your answer... any pointer to the "not easy" way?

**Comment by SD10** [comment]
@pbendersky You would have to modify this function inside of MessageKit internals:

https://github.com/MessageKit/MessageKit/blob/c52d6e42fde9aa0451a3487d354920bece296689/Sources/Layout/MessagesCollectionViewFlowLayout.swift#L417

Here instead of using `labelSize(_:)` you would do your own calculation

**Comment by pbendersky** [comment]
Thank you!

**Comment by BasThomas** [comment]
Want to keep this open to track adding the new property? Maybe better if we open a separate issue?

**Comment by SD10** [comment]
@BasThomas I'm fine with tracking the issue here. This will be a good first issue for version 2.0

**Comment by maxkot900505** [comment]
Hello everyone!

>If there any way to make a chat bubble's width the full width of the messages collection view?

I want to contribute, but I'm not sure yet whether I understand this feature right.  

1) Does this feature means that avatar should be placed above the bottom border of the bubble (because **bubble width really will have full width of the messages collection view, i.e. virtually all horizontal space between left and right borders of the display** )?
2) If so, does the project provides such an opportunity (move avatar above) at the moment?

**Comment by maxkot900505** [comment]
Could, please, someone (related to the making of decisions for the project) clarify my questions above? @SD10 ?

**Comment by SD10** [comment]
Hey @maxkot900505,
By fixed width bubbles we mean the ability to set an explicit width for the size of the bubble.
It' not that each bubble will be the full width, but rather a constant width. So small messages like "lol" and larger ones like "How are you doing?" will be the same size.

I'm not really sure what is the right API for this yet, however, I think JSQMVC has this feature. I would start there for inspiration.

cc @zhongwuzw. ideas?

**Comment by zhongwuzw** [comment]
@SD10 , I think user can override `open func messageContainerSize(for message: MessageType) -> CGSize` and do what he wants?

**Comment by nathantannar4** [comment]
Users can set their own size calculators now, so is this still relevant?

**Comment by SD10** [comment]
Probably not relevant. JSQMVC has an easy way to do this but I'm fine not supporting it. They can do this themselves by overriding the `messageContainerSize` like @zhongwuzw suggested above
