### ISSUE TITLE
Hide messageInputBar after select other TextField

### ISSUE THREAD

**Issue by KuDji** [MessageKit/MessageKit#654]
## General Information
* MessageKit Version: 0.13.3
* iOS Version(s): 11
* Swift Version: 4.2
* Devices/Simulators: iPad Pro 12inch - iOS 11, iPad 10.9 - iOS 10.3
* Reproducible in ChatExample? (Yes/No): Yes

##  What happened?

When i add textField in navigationItem.titleView, messageInputBar are disappear. inputAccessoryView.superView set's to nil

## What did you expect to happen?
When I try to get inputAccessoryView.superView, before I use TextField add set him back all constraint are drop.

**Comment by nathantannar4** [comment]
I believe this is because the `UIViewController` is no longer the first responder (which is required for an `inputAccessoryView` and is thus hidden. There isn't anything we can do about this as we have built the `MessageInputBar` to be a `inputAccessoryView`. I would suggest a) not putting a `UITextField` in the titleView or b) assign a delegate to the `UITextField` and when the textField ends editing, make the `UIViewController` the first responder. I am going to close this for now.
