### ISSUE TITLE
Subclassing MessageFooterView/MessageReusableView

### ISSUE THREAD

**Issue by ilijapuaca** [MessageKit/MessageKit#693]
## General Information

I'm trying to load a custom footer from a nib file. I subclassed `MessageFooterView` and implemented all the necessary data source logic. I then figured that there's this piece of code in `MessageFooterView`:
```swift
    public required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
```

This wouldn't be a problem if it wasn't for the fact that I need to implement this required initializer in my subclass, and I also need to call the `super` implementation as it is the designated initializer.

Am I missing something here? How do I go about returning a custom, nib-defined footer in `func messageFooterView(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageFooterView`

**Comment by austinwright** [comment]
The Apple docs for `UICollectionView.dequeueReusableSupplementaryView(ofKind elementKind: String, withReuseIdentifier identifier: String, for indexPath: IndexPath) -> UICollectionReusableView` state: 

> If you registered a class for the specified identifier and a new cell must be created, this method initializes the cell by calling its init(frame:) method. For nib-based cells, this method loads the cell object from the provided nib file.

So since init(frame:) is overridden by `MessageFooterView`, the compiler forces an implementation of `required init?(coder aDecoder: NSCoder)`.

In your case, you want to register a nib file instead of a class. Currently, `MessagesCollectionView` only has convenience methods for registering a class, not a nib. So you should probably try registering a nib file yourself in your MessagesCollectionView subclass if you haven't already.

Other leads to follow:
- Look at the documentation/be aware of:
`UINib.init(nibName name: String, bundle bundleOrNil: Bundle?)`
`UICollectionView.register(_ nib: UINib?, forSupplementaryViewOfKind kind: String, withReuseIdentifier identifier: String)`
`UICollectionView.dequeueReusableSupplementaryView(ofKind elementKind: String, withReuseIdentifier identifier: String, for indexPath: IndexPath) -> UICollectionReusableView`
- I'm not 100% sure if the `UICollectionView.dequeueReusableSupplementaryView` method above triggers that coder initializer - I didn't have time to try it out. If it is triggering the coder init method when loading the nib file, then it is likely that you will have to create your own UICollectionReusableView subclass rather than subclassing `MessageFooterView` (The implementation is extremely bare bones). The upside there is that you shouldn't have to override any initializers at all.

**Comment by ilijapuaca** [comment]
Thanks for the reply.

> In your case, you want to register a nib file instead of a class. Currently, MessagesCollectionView only has convenience methods for registering a class, not a nib. So you should probably try registering a nib file yourself in your MessagesCollectionView subclass if you haven't already.

I already set everything up using methods you noted in your first bullet above. I can confirm `UICollectionView.dequeueReusableSupplementaryView` triggers coder init method, which is the whole reason I opened the issue.

`func messageFooterView(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageFooterView` explicitly asks for `MessageFooterView` (or subclass of it) to be returned, so implementing `UICollectionReusableView` subclass would require me to override and implement all the logic around `open func collectionView(_ collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, at indexPath: IndexPath) -> UICollectionReusableView`, which because of the way my files are structured is not very convenient.

By the looks of it, the current setup seemengly doesn't support nib defined footers, and it is only due to the fact fatal error is thrown. Making the coder init just call the super implementation makes this whole problem go away.

Not sure how this didn't come up earlier, as this seems like a pretty regular use-case. Should I open a PR for getting rid of fatal errors within initializers across the board?
