### ISSUE TITLE
Section Header View using xib file -> fatalError

### ISSUE THREAD

**Issue by DavidTomic** [MessageKit/MessageKit#715]
Hi,

I am using swift 4, MessageKit 1.0.0-beta.1

I am trying to use section header view from xib file.

Thing is in MessageReusableView class, there is a method:

```
    public required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
```
My app get stuck on fatalError line.

This is my class:

```
class ChatHeaderView: MessageReusableView {
  
  @IBOutlet weak var lblText: UILabel!
    
  func setText(text: String) {
    lblText.text = text
  }
}
```

Can someone help me to make this work, thank you.

**Comment by Luke47** [comment]
This is used for deserialization when you use interface builder / storyboard for a view. 
You need to implement the `init(coder:)` method for this to work. If you do not need own logic, you can let the superclass handle it by writing the following:

```

public required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }

```

**Comment by DavidTomic** [comment]
@Luke47 Thank you for the answer.

But if I add that method in my own class ChatHeaderView, than super will again hit fatalerror in super class which is MessageReusableView.

I can replace method you gave me with method in MessageReusableView, but than I must unlock pod, and on lib upgrade again take care of this.

Is there some better solution? Thank you.

**Comment by SD10** [comment]
@DavidTomic maybe don’t call super? I don’t use storyboards or xibs so I’m not sure on this one

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DavidTomic** [comment]
@SD10 `required init?(coder aDecoder: NSCoder)` requires to call super (or to put fatalError as this lib does)

I think best solution will be to replace `fatalError("init(coder:) has not been implemented")` with `super.init(coder: aDecoder)`

**Comment by Luke47** [comment]
Hm, yeah. That's a tough one for me too. So here are a few workarounds that come to my mind:

1.)  just use a full programmatic approach of building your view (do you only have a single label?) instead of Interface Builder. Then, `required init?(coder aDecoder: NSCoder)` would not be called at all.
2.) Let your `ChatHeaderView` inherit from `UIView` instead (so you can call super) and add an instance of `ChatHeaderView` as a subview to an instance of `MessageReusableView`

Sorry that I can not provide a cleaner solution, but maybe it helps :)

**Comment by DavidTomic** [comment]
@Luke47 I tried programmatically approach, but some wrong behaviour was happening, sections were not showing correctly. That is why I go with the xib approach.

I'll leave as is now in my implementation, I replaced fatalError with super.init in MessageReusableView. Hopefully, this will be changed in some lib version.

Thank you for your help. This lib is great for chat purpose and easy to implement.

**Comment by ranhsd** [comment]
Hi, If you remove this line: 

`fatalError("init(coder:) has not been implemented")`  you can create header view from xib files. 
I think this library should support it because it's much more easy to create custom views using xib and also because it is possible. What I suggest is one of the following: 

1. Remove the **fatalError** and call to super.init (as recommended by @DavidTomic ) 
2. The return the type of both protocol functions: 

```
    func messageHeaderView(for indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageReusableView

    /// The section footer to use for a given `IndexPath`.
    ///
    /// - Parameters:
    ///   - indexPath: The `IndexPath` of the footer.
    ///   - messagesCollectionView: The `MessagesCollectionView` in which this footer will be displayed.
    func messageFooterView(for indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageReusableView
```

should be **UICollectionReusableView** Instead of **MessageReusableView** 

Thanks

**Comment by maxxx777** [comment]
Could `fatalError` be replaced with `super.init` in the next releases to create custom views using xib without change the code of the library.

**Comment by nathantannar4** [comment]
@maxxx777 we would for sure look at a merging a PR if you could do that 😄

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
