### ISSUE TITLE
Re-evaluating MessageCollectionViewCell

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#74]
### Re-evaluating MessageCollectionViewCell
Currently, MessageKit supports a cell structure shown in the figure below:
![messagecollectionviewcell](https://user-images.githubusercontent.com/7445580/29390877-e75e46fe-82b8-11e7-934e-1b85dabe9847.png)

I originally added the `cellTopLabel` and `cellBottomLabel` to this cell because I wanted to be able to top align the avatar with other views and not just the `messageLabel`.

While this allows the layout I was looking for, it also has some drawbacks. Namely, the `cellTopLabel` and `cellBottomLabel` are limited to `UILabels` and multiple views increase the layout complexity for this cell.

### Proposed Solution

We remove the `cellTopLabel`, `cellBottomLabel`, AND the `AvatarView` from the cell. Instead, `cellTopLabel` and `cellBottomLabel` are replaced with their own cells. This should remove the `UILabel` limitation.

We would just need a way to specify if the `MessageCollectionViewCell` or `MessageTopCell` contained the `AvatarView`.

IGListKit does this really well. I could see it being a formal dependency in the future. Why? It makes sense not to reinvent the wheel. 

But for now -- dependencies are off the table. If we make this change we will start with something small, in-house, and see where the architecture leads us.

**Comment by cwalo** [comment]
Just wanted to clarify something. Does using the proposed solution require each message to be its own section as has been discussed elsewhere?

I'm liking the ability to provide any UIView for cell top/bottom. I'm not totally clear where this would put the AvatarView, though.

**Comment by SD10** [comment]
Yeah @cwalo each message is already its own section. Determining where to put the AvatarView is definitely part of the hold up. Sometimes I'd like it in the cell -- other times next to the top cell label.

**Comment by eliburke** [comment]
@SD10 you said about a week back "So I think I’m starting to understand Jesse’s thinking for making each message its own section". I internalized his position a long time ago without being clear on the reasoning, and now I'm being challenged to defend it. 

Reading through the various comments here and on Slack, it sounds like the biggest selling point is configurability: Top and Bottom can contain anything and still be customized / reusable. The main XIB for the message body does not need a whole bunch of components in order to support different looks and feels and alignments. And if an IGListKit friendly layout is desired, developers can lard on additional cell elements easily (likes, actions, reactions, etc).

But there is a downside too, as sections are no longer available to use for grouping by date, or by user (e.g. to add variable bubble appearance or bubble tail behavior as in Messages or Messenger)

Are there other significant pros/cons I'm not seeing? Reducing auto-layout complexity, or cell height calculations, or ...?

**Comment by SD10** [comment]
Hey @eliburke, thanks for your feedback!

I definitely see the tradeoff regarding not being able to group cells by date into a single section. The same for customizing the bubble appearance when grouping messages by user. I still think the bubble customization would be attainable through a 1 message per 1 section layout. Ultimately, I'd have to try it to be sure. Everything is always harder than it seems 😅

I think you see all the pros/cons I'm personally aware of. The biggest pro is customization and reducing complexity of a single cell. 

Overall, it looks like this topic could need some more thought 🤔

**Comment by SD10** [comment]
@eliburke After a bit of thought on this issue -- I don't think we necessarily have to make it an official constraint that we have a **1:1** ratio between Messages and Sections. If this behavior were to change, I don't think it affect much if at all the existing API. Therefore, I'm looking into supporting any sort of grouping: messages by a time span, messages by user, 1 section total, 1 message per section.

Thank you again for driving discussion 👍

**Comment by SD10** [comment]
I’m closing this because it doesn’t look like we’ll be able to remove this constraint. It makes the API too complex. One cell per section is a healthy constraint. IGListKit operates with a similar recommendation.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
