### ISSUE TITLE
AvatarView Sizing

### ISSUE THREAD

**Issue by asaplee** [MessageKit/MessageKit#808]
Hi! So sorry for the flurry of questions asked by myself recently. I had another question/issue about resizing the avatarView. So currently, I am using these two methods:   

```swift
func avatarPosition(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> AvatarPosition {
        return AvatarPosition(horizontal: .natural, vertical: .messageCenter)
    }
    func avatarSize(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> CGSize {
        return CGSize(width: 50, height: 50)
    }
```
But for some reason, these avatars are not being positioned at the center of the message vertically- they remain at the bottom. Also the size adjustment code isn't changing the size of the avatar, even when I set it to something obscene, like 100. Is there some other method I am missing?

**Comment by nathantannar4** [comment]
That method was removed in 1.0. Adjust the MessageSizeCalculators in the `MessagesCollectionViewLayout`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
**How can I remove the `AvatarView` from the cell?**

You can set the `AvatarView` to hidden through the `configureAvatarView(_:AvatarView,for:MessageType,at:IndexPath,in:MessagesCollectionView)` method of `MessagesDisplayDelegate`.

```Swift
func configureAvatarView(_ avatarView: AvatarView, for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) {
  avatarView.isHidden = true
}
```

If you would also like to remove the space the `AvatarView` occupies, you have to change the properties
`outgoingAvatarSize` or `incomingAvatarSize` of the `CellSizeCalculator` object for the respective message to `CGSize.zero` in
`viewDidLoad`.

```Swift
if let layout = messagesCollectionView.collectionViewLayout as? MessagesCollectionViewFlowLayout {
  layout.textMessageSizeCalculator.outgoingAvatarSize = .zero
  layout.textMessageSizeCalculator.incomingAvatarSize = .zero
}
```

If you would like to remove the space the `AvatarView` occupies from all `CellSizeCalculator`s there are
convenience methods so that you do not have to specify it for each `CellSizeCalculator` on `MessagesCollectionViewFlowLayout`.

```Swift
if let layout = messagesCollectionView.collectionViewLayout as? MessagesCollectionViewFlowLayout {
  layout.setMessageIncomingAvatarSize(.zero)
  layout.setMessageOutgoingAvatarSize(.zero)
}
```
