### ISSUE TITLE
Data Detectors styling 

### ISSUE THREAD

**Issue by MacMeDan** [MessageKit/MessageKit#82]
As a user developing with MessageKit I want to be able to style my `Data Detectors` text to make my app look fabulous even with custom backgrounds. Currently any text that is detected as a Phone Number, Address or email is a black underlined set of words. 

![screen shot 2017-08-25 at 3 27 02 pm](https://user-images.githubusercontent.com/6182351/29733336-e1b15cf8-89a9-11e7-90ac-db946340f6b3.png)

We should be able to easily configure this with a convenience method.

**Comment by SD10** [comment]
@MacMeDan  You can customize this using the `addressAttributes: [String: Any]` property of `MessageLabel`. The thing is -- you can only change attributes that don't change the size of the layout, `eg) underline, color, underline color`. If you do, the layout won't render correctly.

This is likely to remain a limitation for awhile because fixing it requires the collectionView to know what attributes you're using in advance and also to parse the text for the detectors.

**Comment by MacMeDan** [comment]
I would suggest that we make a method that limits it to just those options `underline, color, underline color`. This way we do not have people breaking the layout when they style Data Detectors.

**Comment by SD10** [comment]
@MacMeDan I kind of think that too, I even added it at first but removed it because there were 20+ properties. The thing is it doesn't offer any real protection. For example: If you set a different font for the message label than the one set in the layout object -- you will break the layout. We can't make these properties of UILabel private. This just has to be something that is made aware to people as a rule for using the project.

**Comment by SD10** [comment]
Closing this because we have this functionality in `v0.6.0`

**Comment by agordeev** [comment]
@SD10 How do I access `addressAttributes` from a subclass of `MessagesViewController`?

**Comment by SD10** [comment]
@agordeev There's no way to do this from the `MessagesViewController`. I'm looking to add a delegate method to make this possible. It's blocked by #356
