### ISSUE TITLE
Incoming messages are aligned left 

### ISSUE THREAD

**Issue by topslave** [MessageKit/MessageKit#823]
Hi 
I  created a chat application using Parse SDK and livequeries,  all the incoming messages are aligned to left( as reciever) even the ones with the sender label are aligned left.  The new messages being sent are aligned right as expected. None of the MessagesDisplayDelegate methods are fired.    messagesCollectionView.messagesDisplayDelegate = self is set to self on viewDidload. What am I doing wrong ? Any help would be much appreciated.

**Comment by brandon-haugen** [comment]
Hey @CurItUK, it sounds like you are experiencing a different issue but can you verify that in your `viewDIdLoad()` that you call `super.viewDidLoad()`?

Since the messages are displaying on the screen (it sounds like they are), I don't think you are running into the same issue as #819, let's rule that out though as being the issue.
