### ISSUE TITLE
Why media item had an image property on it? Could this property lead to memory pressure?

### ISSUE THREAD

**Issue by moldovaniosif** [MessageKit/MessageKit#877]
Hi I had look over MediaItem protocol which ask for an image if the message is a photo. I had printed the protocol below:
```swift
public protocol MediaItem {

    var url: URL? { get }

    var image: UIImage? { get }

    var placeholderImage: UIImage { get }

    var size: CGSize { get }

}
```
I was thinking to a conversation that may had hundres of phots, keeping all of them in memory could lead to memory pressure. Why did not relay only on the "url" property and fetch the image based on the url path.
Is there a specific reason why the photo message should keep the iamge in memory?

**Comment by nathantannar4** [comment]
@moldovaniosif the problem with only taking the URL is that now MessageKit has to handle image fetching and caching, because cells are reused in a collection view so you can't just fetch it on the cell load. We have the `UIImage` properties for basic use. More advanced use pairs the `URL` with something like Kingfisher. And storing lots of strings isn't a big memory issue. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
It's difficult to build a framework that handles all the representations of the client's data. By default MessageKit will use the `image` property but this is optional. If you don't want to use it (and as you mentioned I suggest you just use URL + AlamofireImage, Kingfisher, or SDWebImage etc.) then just provide the URL and handle the assignment of the image with the `configureMediaView` delegate method yourself
